# -*- coding: utf-8 -*-
"""numpy3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pN7cLVKbws0T01pYozI3IV9z3LwjXLQb
"""

import numpy as np
temp = np.arange(48)
print(temp)
temp_3D = temp.reshape(4,3,4)
temp_2D = temp.reshape(6,8)
print(temp_3D)
print(temp_2D)

